### ISSUE TITLE
盘子清除物品NBT的BUG

### ISSUE THREAD

**Issue by TskimiSeiran** [Mangopill/Fruit-Stack#2]
将含有nbt的物品（如掉耐久或有附魔）放入本模组盘子中，再取出来会导致所有NBT数据清空。

**Comment by TskimiSeiran** [comment]
以及，机械动力的蓝图可以打印出酿造桶的nbt

**Comment by Mangopill** [comment]
> 将含有nbt的物品（如掉耐久或有附魔）放入本模组盘子中，再取出来会导致所有NBT数据清空。

修了
