### ISSUE TITLE
Crash when stepping on a clay oven

### ISSUE THREAD

**Issue by medsal15** [Mangopill/Fruit-Stack#4]
Minecraft crashed when I walked on a clay oven

Crash log: https://pastebin.com/UBDvHZLD

**Comment by Mangopill** [comment]
> 当我走在粘土烤箱上时，《我的世界》崩溃了
> 
> 崩溃日志：https://pastebin.com/UBDvHZLD

Currently, 1.20.1 has not been completed, and it will be repaired along the way

**Comment by medsal15** [comment]
Seems to have been fixed in the most recent version 👍
